### ISSUE TITLE
WhatsappApiException not expose the status code

### ISSUE THREAD

**Issue by pcomp96** [Bindambc/whatsapp-business-java-api#107]
Hi @Bindambc,

I resumed developing the integration I was implementing, while I was wrapping the CRUD API of the whatsapp media files to expose them to the integrating system, I noticed that the WhatsappApiException class has the WhatsappApiError object as a private member. It does not have a method that returns the status code of the checked exception. Being a REST call, it would need a `getStatusCode ` method at least to return the status code occurred in the call.

The API I'm testing is the `retrieveMediaUrl` by mediaId.

![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/80928861/ca9a4cc8-6922-49b2-8c9e-719889c8b1a2)

When I call the API with an ID that doesn't exist I would like to return 404 from my API but I have no way to discriminate that

![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/80928861/7ccf8eab-a42b-44d4-a897-f864a6ed7ff9)

Using a provider, In this case, i catch the exception but i have to return 500 because i don't have the status code.

The exception I get is the following.

![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/80928861/90d35a2b-f8c7-47a1-ab42-f1c194e05ef5)

Would it be expensive to add a `statusCode `return?

Waiting for your reply, I hope I was helpful. 

Thank you,
Giuseppe

**Comment by Bindambc** [comment]
Hello @pcomp96 ,

I can modify the class `WhatsappApiException `by adding a method called `getWhatsappApiError()` that will allow obtaining the error object. Within the error object, you will be able to check the error codes sent by WhatsApp API.

Could this help you?

![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/7831956/b0ab7daf-d2ba-4d71-824e-0cd2219ff9e7)

**Comment by Bindambc** [comment]
@pcomp96  
I could also return the HTTP code, but I'm not sure if it would be helpful. Note that in the case of media not found, the HTTP code is 400.
![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/7831956/b25ed3a9-925d-4f27-be71-abc2ac301b80)

**Comment by pcomp96** [comment]
Sorry for the late reply @Bindambc,

> I can modify the class `WhatsappApiException` by adding a method called `getWhatsappApiError()` that will allow obtaining the error object. Within the error object, you will be able to check the error codes sent by WhatsApp API.

Yes is perfect because the class `WhatsappApiException` return only the message of the exception throwed from API.


> I could also return the HTTP code, but I'm not sure if it would be helpful. Note that in the case of media not found, the HTTP code is 400.

I think that is the best way to register the HTTP status code in the `WhatsappApiError` and expose it with `public int getHttpStatusCode()`.

I hope that is useful 😀.

Thanks,
Giuseppe.
