### ISSUE TITLE
Messages not being delivered to users.

### ISSUE THREAD

**Issue by tmoreira2020** [Bindambc/whatsapp-business-java-api#128]
Hi there, I have an application up and running that interact with users daily in an automated way. I'm able to see in my logs that the messages were sent successfully BUT customer aren't getting it into their cell phones. I have a valid Whatsapp Business account with real number but not verified yet.
Any help is appreciated.

**Comment by Bindambc** [comment]
Hello, @tmoreira2020 . 

The WhatsApp API enables sending messages to anyone at any time, albeit with certain limitations:

- If your application initiates the conversation, it must be done using a template that has been pre-approved by WhatsApp.
- If your customer starts the conversation, you can send messages without a template within a 24-hour period. After this timeframe, you can only continue the conversation with a valid template.

This might be applicable to your situation.

**Comment by tmoreira2020** [comment]
Thanks @Bindambc for the reply!

> If your application initiates the conversation, it must be done using a template that has been pre-approved by WhatsApp.
I didn't know about that I will give a try. One questions about templates: is it possible to set an id for the button besides the label? Didn't find how to do it in the UI.

Thanks
