### ISSUE TITLE
Response Parsing Error.

### ISSUE THREAD

**Issue by ShehzadNazir13** [Bindambc/whatsapp-business-java-api#129]
I am receiving this error from the template message response.

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "message_status" (class com.whatsapp.api.domain.messages.response.Message), not marked as ignorable (one known property: "id"])

Looks like maybe the API response model changed. So I have looked at both the facebook response text and model and found inconsistency.

Facebook API response example:

![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/134699140/a39dedb3-a4bb-4e16-a6e9-07f6e4bfe907)

Library response Model:

![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/134699140/7d5bacc3-1cc5-4e60-ba19-f6bb4cc36663)

Can you take a look at it or maybe make the model ignore-unknow so Jackson won't raise any issues while parsing.
That would really be helpful.

**Comment by tmoreira2020** [comment]
This issue was already raised in #125
