### ISSUE TITLE
Receiving Error when sending message using template.

### ISSUE THREAD

**Issue by isanketsaha** [Bindambc/whatsapp-business-java-api#135]
This error is coming when receiving response after sendMessage().

`Resolved [com.whatsapp.api.exception.WhatsappApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "message_status" (class com.whatsapp.api.domain.messages.response.Message), not marked as ignorable (one known property: "id"]).`

**Comment by santhoshda** [comment]
@isanketsaha Any workaround for this?

**Comment by Bindambc** [comment]
Hello @isanketsaha / @santhoshda 
I'm checking this issue.

**Comment by Bindambc** [comment]
Fixed - version v0.4.1
https://github.com/Bindambc/whatsapp-business-java-api/releases/tag/v0.4.1
