### ISSUE TITLE
fork to use in quarkus

### ISSUE THREAD

**Issue by fiorenzino** [Bindambc/whatsapp-business-java-api#14]
Hi,

i would like to use big part of your code in a [quarkus.io](quarkus.io) extension:

*   it means we will remove all libraries not compliant (ie: retrofit and okhttp3)
*   we will add rest endpoint to receives webhook events
*   we will generate a docker images, with env parameters to configure dynamically the container

The project name could be: qwaba (quarkus + waba).  
And we can support you to add (eventual) missing features.  
What do you think about?   
Naturally the project and the code will be opensource in github.

Thanks for your work!

**Comment by Bindambc** [comment]
Hello @fiorenzino,

I appreciate your interest in using my code. I'm happy to see it being repurposed for a Quarkus extension.

I fully support this and I think it's a great idea to remove the non-compliant libraries. I look forward to seeing the result and I'm open to collaborating and supporting you in adding any missing features.

"Qwaba" is a nice name.

Thanks.
