### ISSUE TITLE
Error in Parsing WhatsApp Business Phone Number Response - New fields

### ISSUE THREAD

**Issue by valentinogiardino** [Bindambc/whatsapp-business-java-api#141]
Encountered an error while parsing the response from WhatsApp Business Phone Numbers API after the September 12, 2023 update. The issue seems to be related to a missing property, platform_type, in the PhoneNumber class causing deserialization to fail:

``
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"platform_type\" (class com.whatsapp.api.domain.phone.PhoneNumber), not marked as ignorable (6 known properties: \"verified_name\", \"code_verification_status\", \"name_status\", \"display_phone_number\", \"id\", \"quality_rating\"])\n at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 225] (through reference chain: com.whatsapp.api.domain.phone.PhoneNumber[\"platform_type\"])
``

[_CHANGELOG September 12, 2023_](https://developers.facebook.com/docs/whatsapp/business-platform/changelog#september-12--2023)
- Added **throughput** and **platform_type** fields to [WhatsApp Business Phone Numbers](https://developers.facebook.com/docs/graph-api/reference/whats-app-business-account-to-number-current-status/).

- Added new [WhatsApp Business Account Access](https://developers.facebook.com/docs/whatsapp/business-management-api/get-started#whatsapp-business-account-control) levels for more granular control.

**Comment by Bindambc** [comment]
https://github.com/Bindambc/whatsapp-business-java-api/releases/tag/v0.4.1
