### ISSUE TITLE
Using the library for Whatstapp API version 19

### ISSUE THREAD

**Issue by OldKalash7** [Bindambc/whatsapp-business-java-api#178]
Hello. I'm currently building an application that needs to communicate with whatsapp api. In the meta panel, the version of the api it's 19
![image](https://github.com/Bindambc/whatsapp-business-java-api/assets/43732524/d9ba9fc7-51cc-4113-8a13-c28e2ae1b511)

I'm trying to deserialize the test payload of a  message webhook provided by meta, using the WebHook class.

```json
{
  "field": "messages",
  "value": {
    "messaging_product": "whatsapp",
    "metadata": {
      "display_phone_number": "16505551111",
      "phone_number_id": "123456123"
    },
    "contacts": [
      {
        "profile": {
          "name": "test user name"
        },
        "wa_id": "16315551181"
      }
    ],
    "messages": [
      {
        "from": "16315551181",
        "id": "ABGGFlA5Fpa",
        "timestamp": "1504902988",
        "type": "text",
        "text": {
          "body": "this is a text message"
        }
      }
    ]
  }
}
```
I get the following error:
`Unrecognized field "field" (class com.whatsapp.api.domain.webhook.WebHookEvent), not marked as ignorable (2 known properties: "entry", "object"])`

I saw the payload you provided in the example: https://github.com/Bindambc/whatsapp-business-java-api/blob/main/src/test/java/com/whatsapp/api/examples/WebHookExample.java 

And it's different. This is expected due to the diffent versions (I'ts stated that the library supports 16)? Can the Webhook class be extended somehow to support this new type of payload?

Thanks in advance Mauricio.

**Comment by Bindambc** [comment]
Hello @OldKalash7,

 I believe the JSON you posted is incomplete. In the payload, there are the fields 'object' and 'entry.' See the example below, which I also obtained from the v19 API
 
```json
{
   "object": "whatsapp_business_account",
   "entry": [
      {
         "id": "0",
         "changes": [
            {
               "field": "messages",
               "value": {
                  "messaging_product": "whatsapp",
                  "metadata": {
                     "display_phone_number": "16505551111",
                     "phone_number_id": "123456123"
                  },
                  "contacts": [
                     {
                        "profile": {
                           "name": "test user name"
                        },
                        "wa_id": "16315551181"
                     }
                  ],
                  "messages": [
                     {
                        "from": "16315551181",
                        "id": "ABGGFlA5Fpa",
                        "timestamp": "1504902988",
                        "type": "text",
                        "text": {
                           "body": "this is a text message"
                        }
                     }
                  ]
               }
            }
         ]
      }
   ]
}
```
