### ISSUE TITLE
modify the `README.md` file

### ISSUE THREAD

**Issue by Bindambc** [Bindambc/whatsapp-business-java-api#37]
We need to modify the README.md to make it look more attractive and to make the documentation easier to read. Suggestions for changes are welcome, and text corrections are also appreciated.

**Comment by vishalsingh2972** [comment]
@Bindambc could you assign this to me if it is still open, I spot few text corrections that need to be made!

**Comment by vishalsingh2972** [comment]
@Bindambc made few changes could you please check and merge the PR https://github.com/Bindambc/whatsapp-business-java-api/pull/81
