### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fabiofavale85** [Bindambc/whatsapp-business-java-api#40]
The library works very well, the only difference i noted using message template is that it is not possible to edit message button. 
The configuration is possible only at template creation time (MessageTemplate), but using TemplateMessage adding ComponentType.BUTTONS there is no way to pass subtype, payload, text, url on the buttons. Thanks for your work.

**Comment by Bindambc** [comment]
Hello @fabiofavale85 ,
The changes and fixes to message templates are now available in version **v0.2.0**.

**Comment by fabiofavale85** [comment]
It works very well. Great Job!!! @Bindambc
