### ISSUE TITLE
Languages support

### ISSUE THREAD

**Issue by Bindambc** [Bindambc/whatsapp-business-java-api#7]
We need to add all supported languages by Whatsapp.  Supported Languages can be added in Language enum.

See the enum class [here](https://github.com/Bindambc/whatsapp-business-java-api/blob/main/src/main/java/com/whatsapp/api/domain/templates/Language.java)

We appreciate your help.

**Comment by mahir118** [comment]
Hi, can you provide some more details on the issue?

**Comment by Bindambc** [comment]
> Hi, can you provide some more details on the issue?

Hello @mahir118 , thank you for asking. This is a very simple issue, just add more language options to the enum class ["Language.java"](https://github.com/Bindambc/whatsapp-business-java-api/blob/main/src/main/java/com/whatsapp/api/domain/templates/Language.java). The languages supported by WhatsApp can be found on this [page](https://developers.facebook.com/docs/whatsapp/api/messages/message-templates#)

**Comment by gaurav9777** [comment]
Hi @Bindambc can you assign this task to me??
If I understand the issue , i just have to add all the languages from [https://developers.facebook.com/docs/whatsapp/api/messages/message-templates#](this ) page in Language.java class

**Comment by Bindambc** [comment]
> Hi @Bindambc can you assign this task to me?? If I understand the issue , i just have to add all the languages from [https://developers.facebook.com/docs/whatsapp/api/messages/message-templates#](this) page in Language.java class

Hi @gaurav9777, thanks for your contribution.
