### ISSUE TITLE
WebHookExample

### ISSUE THREAD

**Issue by eos1d3** [Bindambc/whatsapp-business-java-api#83]
Hi,

I am studying how to use this library. The only thing I am confused is how to use WebHook. From WebHookExample, it does not setup Token or URL. Does this library need another web server running to receive WebHook events? And how to link the server to this library?

I also do not find any user callback to get WebHook event, nor any WebHook subscription in this library.

Need further clarifications for this. Thanks!

**Comment by pcomp96** [comment]
Hello @eos1d3,

> From WebHookExample, it does not setup Token or URL.

You should implement the webhook APIs. 
This library provides an interface for the event received on the webhook from WhatsApp.

You must implement 2 endpoint without authorization

1. **GET** - To verify the webhook with WA
2. **POST** - To receive the event when WA send it.

This is an example of verify endpoint:

   ``` java
@GET
@Path("/webhook")
public Response verify(@NotNull @QueryParam("hub.mode") String mode,
                        @NotNull @QueryParam("hub.challenge") String challenge,
                        @NotNull @QueryParam("hub.verify_token") String verifyToken);
```
------
This is an example of processEvent endpoint:
``` java
@POST
@Path("/webhook")
public Response processEvent(@NotNull String payload);
```

The examples are written with Quarkus and Java 11.

1) The token must be verified from you in business logic.
2) The URL must be in HTTPS and set it into https://developers.facebook.com/apps/{YOUR_APP_ID}/whatsapp-business/wa-settings/?business_id={YOUR_BUSINESS_ID}
3) See this guide to set the webhook.. 
https://developers.facebook.com/docs/whatsapp/cloud-api/get-started#configure-webhooks
4) To test fastly I recommend you using Glitch or Heroku.


Hope this may be helpful!

**Comment by eos1d3** [comment]
Thanks a lot. I will try later with a real test.

**Comment by Bindambc** [comment]
Hello,

Thanks @pcomp96 for your contribution.

@eos1d3, as @pcomp96 mentioned, you need to implement the endpoints for the webhook.

You can use this library to deserialize an event received on the webhook:

```java
public void processEvent(@NotNull String payload);
       WebHookEvent event = WebHook.constructEvent(payload)
  ```

**Comment by gustavobrian** [comment]
Hi, thanks for your work... I need full sample the webhook ?

**Comment by sradityaa** [comment]
please provide full code for webhook implementation. Thank You

**Comment by sradityaa** [comment]
> Halo@eos1d3,
> 
> > Dari WebHookExample, itu tidak menyiapkan Token atau URL.
> 
> Anda harus mengimplementasikan API webhook. Pustaka ini menyediakan antarmuka untuk acara yang diterima di webhook dari WhatsApp.
> 
> Anda harus menerapkan 2 titik akhir tanpa izin
> 
> 1. **GET** - Untuk memverifikasi webhook dengan WA
> 2. **POST** - Untuk menerima acara saat WA mengirimkannya.
> 
> Ini adalah contoh titik akhir verifikasi:
> 
> ```java
> @GET
> @Path("/webhook")
> public Response verify(@NotNull @QueryParam("hub.mode") String mode,
>                      @NotNull @QueryParam("hub.challenge") String challenge,
>                      @NotNull @QueryParam("hub.verify_token") String verifyToken);
> ```
> 
> Ini adalah contoh titik akhir processEvent:
> 
> ```java
> @POST
> @Path("/webhook")
> public Response processEvent(@NotNull String payload);
> ```
> 
> Contohnya ditulis dengan Quarkus dan Java 11.
> 
> 1. Token harus diverifikasi dari Anda dalam logika bisnis.
> 2. URL harus dalam HTTPS dan disetel ke [https://developers.facebook.com/apps/{YOUR_APP_ID}/whatsapp-business/wa-settings/?business_id={YOUR_BUSINESS_ID}](https://developers.facebook.com/apps/%7BYOUR_APP_ID%7D/whatsapp-business/wa-settings/?business_id=%7BYOUR_BUSINESS_ID%7D)
> 3. Lihat panduan ini untuk mengatur webhook.. 
>    https://developers.facebook.com/docs/whatsapp/cloud-api/get-started#configure-webhooks
> 4. Untuk menguji dengan cepat saya sarankan Anda menggunakan Glitch atau Heroku.
> 
> Semoga ini bisa membantu!

please provide full code for webhook implementation. Thank You
