### ISSUE TITLE
Set proxy for okhttp3 client

### ISSUE THREAD

**Issue by pcomp96** [Bindambc/whatsapp-business-java-api#84]
Hi Maurício,
first of all, congratulations on the creation of this library, it is easy to understand the use and is implemented with a few steps. 😄

I'm still on testing phase and one things that I'm having hard time it is set a proxy for the `WhatsappBusinessCloudApi`.

Looking at the source code I noticed that the okhttp3 client when instantiated is not set any proxy and there is no way to change the settings of the client used.

Go to [WhatsappApiServiceGenerator](https://github.com/Bindambc/whatsapp-business-java-api/blob/f7ddb968bfa5283b117b017cead2301a2de1c26d/src/main/java/com/whatsapp/api/WhatsappApiServiceGenerator.java#L49)
 ```java
   static {

        sharedClient = new OkHttpClient.Builder()//
                .callTimeout(20, TimeUnit.SECONDS)//
                .pingInterval(20, TimeUnit.SECONDS)//
                .build();
    }
```

Is there a way to do this without having to tamper with the source code by configuring some properties or should this feature be implemented?

Thanks!

**Comment by Bindambc** [comment]
Hello @pcomp96, 

this feature needs to be implemented and I am currently looking for a way to do it.

One option is to modify the `WhatsappApiServiceGenerator` class by changing `private static final OkHttpClient sharedClient` to `public static OkHttpClient sharedClient`.

This change would allow us to override the `sharedClient` whenever necessary. For example:

```java

WhatsappApiServiceGenerator.sharedClient = WhatsappApiServiceGenerator.sharedClient
        .newBuilder()
        .proxy(new Proxy(Type.DIRECT, null))
        .build();

WhatsappApiFactory factory = WhatsappApiFactory.newInstance(TestConstants.TOKEN);
WhatsappBusinessCloudApi whatsappBusinessCloudApi = factory.newBusinessCloudApi();

var message = MessageBuilder.builder()
        .setTo(PHONE_NUMBER_1)
        .buildTextMessage(new TextMessage()
                .setBody(Formatter.bold("Hello world!") + "\nSome code here: \n" + Formatter.code("hello world code here"))
                .setPreviewUrl(false));

MessageResponse messageResponse = whatsappBusinessCloudApi.sendMessage(PHONE_NUMBER_ID, message);

```

Another option is to include the `Proxy` in the `WhatsappApiConfig` class and then use it in the `WhatsappApiServiceGenerator` This approach would prevent direct changes to the `sharedClient`.

What do you think about these options? Is there another solution or approach that you would suggest?

Thanks.

**Comment by pcomp96** [comment]
@Bindambc thanks for the reply 👍🏻 
> One option is to modify the `WhatsappApiServiceGenerator` class by changing `private static final OkHttpClient sharedClient` to `public static OkHttpClient sharedClient`.

It seems to me the fastest change to allow you to set a proxy but I think it is not the best.

From the documentation [OkHttp3 proxy-selector](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/proxy-selector/) and from the source code of OkHttp3 I see that it uses `ProxySelector.getDefault()` to set the default proxy to use.
But the authenticator variable is set by default `proxyAuthenticator = Authenticator.NONE;` 

```java
   public Builder() {
      dispatcher = new Dispatcher();
      protocols = DEFAULT_PROTOCOLS;
      connectionSpecs = DEFAULT_CONNECTION_SPECS;
      eventListenerFactory = EventListener.factory(EventListener.NONE);
      proxySelector = ProxySelector.getDefault();
      cookieJar = CookieJar.NO_COOKIES;
      socketFactory = SocketFactory.getDefault();
      hostnameVerifier = OkHostnameVerifier.INSTANCE;
      certificatePinner = CertificatePinner.DEFAULT;
      proxyAuthenticator = Authenticator.NONE;
      authenticator = Authenticator.NONE;
      connectionPool = new ConnectionPool();
      dns = Dns.SYSTEM;
      followSslRedirects = true;
      followRedirects = true;
      retryOnConnectionFailure = true;
      connectTimeout = 10_000;
      readTimeout = 10_000;
      writeTimeout = 10_000;
      pingInterval = 0;
    }
```
This  `.proxy(new Proxy(Type.DIRECT, null))` can be set by creating a class like the following example :

```java
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.ProxySelector;
import java.net.SocketAddress;
import java.net.URI;
import java.net.Proxy.Type;
import java.util.Collections;
import java.util.List;

import lombok.extern.slf4j.Slf4j;

public class CustomProxySelector extends ProxySelector {
    private final Proxy proxy;

    public CustomProxySelector(Proxy proxy) {
        this.proxy = proxy;
    }

    public CustomProxySelector(Type type, String host, int port) {
        this.proxy = new Proxy(type, new InetSocketAddress(host, port));
    }

    @Override
    public List<Proxy> select(URI uri) {
        return Collections.singletonList(proxy);
    }

    @Override
    public void connectFailed(URI uri, SocketAddress sa, IOException ioe) {
        log.info("Failed to connect at custom proxy {} via {} due to {}", uri, sa, ioe);
    }
}
```
Just set the application startup the Proxy in this way and the okhttp3 client will use this by default.

```java
ProxySelector.setDefault(new CustomProxySelector(Type.HTTP, "<PROXY_HOST>", "<PROXY_PORT>"));
```

There would remain the problem of having to set the authentication credentials to be used for the proxy,from the documentation [OkHttp3 proxy-authenticator](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/proxy-authenticator/).

> If unset, the [no authentication will be attempted](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-authenticator/-companion/-n-o-n-e/).

A class like the following `CustomProxyAuthenticator ` would be enough to implement it in the client by adding it when it is instantiated.
```java
public class CustomProxyAuthenticator implements Authenticator {
    private String proxyUsername;
    private String proxyPassword;

    
    public CustomProxyAuthenticator(String username,String password){
         super();
         this.proxyUsername=username;
         this.proxyPassword=password;
     }

    @Override
    public Request authenticate(Route route, Response response) throws IOException {
        String credential = Credentials.basic(proxyUsername, proxyPassword);
        return response.request().newBuilder()
                .header("Proxy-Authorization", credential)
                .build();
    }
}
```

```java
 sharedClient = new OkHttpClient.Builder()//
                .callTimeout(20, TimeUnit.SECONDS)//
                .pingInterval(20, TimeUnit.SECONDS)//
                .proxyAuthenticator(new CustomProxyAuthenticator("<PROXY_USERNAME>","<PROXY_PWD>"))
                .build();
```

What do you think? 

Thanks! :)

**Comment by Bindambc** [comment]
> @Bindambcobrigado pela resposta 👍🏻
> 
> > Uma opção é modificar a `WhatsappApiServiceGenerator`classe alterando `private static final OkHttpClient sharedClient`para `public static OkHttpClient sharedClient`.
> 
> Parece-me a mudança mais rápida para permitir que você defina um proxy, mas acho que não é o melhor.
> 
> Na documentação do [seletor de proxy OkHttp3](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/proxy-selector/) e no código-fonte do OkHttp3, vejo que ele usa `ProxySelector.getDefault()`para definir o proxy padrão a ser usado. Mas a variável do autenticador é definida por padrão`proxyAuthenticator = Authenticator.NONE;`
> 
> ```java
>    public Builder() {
>       dispatcher = new Dispatcher();
>       protocols = DEFAULT_PROTOCOLS;
>       connectionSpecs = DEFAULT_CONNECTION_SPECS;
>       eventListenerFactory = EventListener.factory(EventListener.NONE);
>       proxySelector = ProxySelector.getDefault();
>       cookieJar = CookieJar.NO_COOKIES;
>       socketFactory = SocketFactory.getDefault();
>       hostnameVerifier = OkHostnameVerifier.INSTANCE;
>       certificatePinner = CertificatePinner.DEFAULT;
>       proxyAuthenticator = Authenticator.NONE;
>       authenticator = Authenticator.NONE;
>       connectionPool = new ConnectionPool();
>       dns = Dns.SYSTEM;
>       followSslRedirects = true;
>       followRedirects = true;
>       retryOnConnectionFailure = true;
>       connectTimeout = 10_000;
>       readTimeout = 10_000;
>       writeTimeout = 10_000;
>       pingInterval = 0;
>     }
> ```
> 
> Isso `.proxy(new Proxy(Type.DIRECT, null))`pode ser definido criando uma classe como o exemplo a seguir:
> 
> ```java
> import java.io.IOException;
> import java.net.InetSocketAddress;
> import java.net.Proxy;
> import java.net.ProxySelector;
> import java.net.SocketAddress;
> import java.net.URI;
> import java.net.Proxy.Type;
> import java.util.Collections;
> import java.util.List;
> 
> import lombok.extern.slf4j.Slf4j;
> 
> public class CustomProxySelector extends ProxySelector {
>     private final Proxy proxy;
> 
>     public CustomProxySelector(Proxy proxy) {
>         this.proxy = proxy;
>     }
> 
>     public CustomProxySelector(Type type, String host, int port) {
>         this.proxy = new Proxy(type, new InetSocketAddress(host, port));
>     }
> 
>     @Override
>     public List<Proxy> select(URI uri) {
>         return Collections.singletonList(proxy);
>     }
> 
>     @Override
>     public void connectFailed(URI uri, SocketAddress sa, IOException ioe) {
>         log.info("Failed to connect at custom proxy {} via {} due to {}", uri, sa, ioe);
>     }
> }
> ```
> 
> Basta definir a inicialização do aplicativo Proxy dessa maneira e o cliente okhttp3 usará isso por padrão.
> 
> ```java
> ProxySelector.setDefault(new CustomProxySelector(Type.HTTP, "<PROXY_HOST>", "<PROXY_PORT>"));
> ```
> 
> Restaria o problema de ter que definir as credenciais de autenticação a serem usadas para o proxy, da documentação [OkHttp3 proxy-authenticator](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/proxy-authenticator/) .
> 
> > Se não for definido, a [autenticação não será tentada](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-authenticator/-companion/-n-o-n-e/) .
> 
> Uma classe como a seguinte `CustomProxyAuthenticator `seria suficiente para implementá-lo no cliente adicionando-o quando for instanciado.
> 
> ```java
> public class CustomProxyAuthenticator implements Authenticator {
>     private String proxyUsername;
>     private String proxyPassword;
> 
>     
>     public CustomProxyAuthenticator(String username,String password){
>          super();
>          this.proxyUsername=username;
>          this.proxyPassword=password;
>      }
> 
>     @Override
>     public Request authenticate(Route route, Response response) throws IOException {
>         String credential = Credentials.basic(proxyUsername, proxyPassword);
>         return response.request().newBuilder()
>                 .header("Proxy-Authorization", credential)
>                 .build();
>     }
> }
> ```
> 
> ```java
>  sharedClient = new OkHttpClient.Builder()//
>                 .callTimeout(20, TimeUnit.SECONDS)//
>                 .pingInterval(20, TimeUnit.SECONDS)//
>                 .proxyAuthenticator(new CustomProxyAuthenticator("<PROXY_USERNAME>","<PROXY_PWD>"))
>                 .build();
> ```
> 
> O que você acha?
> 
> Obrigado! :)

Thanks, @pccomp96. I've read your comment and looked over the OkHttp documentation. I'll work on adding this proxy configuration to the next version. If you've already written some code to handle the proxy, feel free to submit a pull request.
