### ISSUE TITLE
Error on messages webhook

### ISSUE THREAD

**Issue by gbordoni** [Bindambc/whatsapp-business-java-api#86]
When sending a mesage fails, the library fails to parse the content received on the wbehook, as now there is a new property "href" on the [Error](https://github.com/Bindambc/whatsapp-business-java-api/blob/main/src/main/java/com/whatsapp/api/domain/webhook/Error.java) class which isn't yet defined:

![image](https://user-images.githubusercontent.com/13774052/234401205-6888f734-8bcc-4d4e-9bd7-aa81cafe7788.png)

I tired to open a new pull request but couldn't do it. In any case, the fix should be very easy.

**Comment by Bindambc** [comment]
Thank you @gbordoni  for reporting this bug. The fix is now available in version [v0.3.1](https://github.com/Bindambc/whatsapp-business-java-api/releases/tag/v0.3.1).
