### ISSUE TITLE
Unable to retrieve templates

### ISSUE THREAD

**Issue by niguzman** [Bindambc/whatsapp-business-java-api#91]
Hi! First of all, thanks for this incredible API!

I'm having a small problem, I'm trying to retrieve all my templates but I'm receiving this error: `Unrecognized field "previous_category" (class com.whatsapp.api.domain.templates.response.Template), not marked as ignorable (6 known properties: "status", "components", "language", "name", "category", "id"])`

I saw in my templates and the sample template "hello_world" has a message saying _This template category was updated from "Account update" to "Marketing"._ and in the JSON response from CloudAPI I can see that new field previous_category that I think is not included in this API.

<img width="810" alt="Screenshot 2023-05-02 at 2 19 58 PM" src="https://user-images.githubusercontent.com/48304981/235751959-774c902c-ebf4-4f6f-81a8-c53219fa4bdf.png">

Thanks!

**Comment by Bindambc** [comment]
Thank you @niguzman for reporting this bug. The fix is now available in version [v0.3.2](https://github.com/Bindambc/whatsapp-business-java-api/releases/tag/v0.3.2).
